name = "TETB"
uuid = "0d4be8d3-4503-476c-b33f-e073dd414f32"
authors = ["Antonio Morales Perez <antonio.morales@dipc.org>, Thomas Christensen <thomas@dtu.dk>, and contributors"]
version = "0.0.1"

[deps]
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPBUtils = "a5feb4ea-5495-4677-96f8-dddb76c9eb4c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PhotonicBandConnectivity = "d7bc101a-f969-4292-96d7-1ebdabfa903f"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SymmetricTightBinding = "793e0360-0e47-4c52-9513-43d75d53c7d0"
SymmetryBases = "cb68ded9-7e8c-45d3-bc66-19b5867c0467"

[sources]
MPBUtils = {url = "https://github.com/thchr/MPBUtils.jl"}
PhotonicBandConnectivity = {url = "https://github.com/thchr/PhotonicBandConnectivity.jl"}
SymmetricTightBinding = {path = "./SymmetricTightBinding"}
SymmetryBases = {url = "https://github.com/thchr/SymmetryBases.jl"}

[compat]
Crystalline = "0.6.17"
LinearAlgebra = "1.11.0"
MPBUtils = "0.2"
Optim = "1.12.0"
PhotonicBandConnectivity = "0.5"
PythonCall = "0.9.24"
Reexport = "1"
SymmetricTightBinding = "0.1.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
